# Generated by Django 6.0.3 on 2026-04-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='used_credits',
            field=models.BooleanField(default=False),
        ),
    ]
